# Project name
set(PACKAGE_NAME SRC)

get_property(IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

if (NOT IS_MULTI_CONFIG AND NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Debug CACHE STRING "Choose the type of build, options are: Debug Release" FORCE)
endif ()

if (UNIX)
    set(THREADS_PREFER_PTHREAD_FLAG ON)
endif ()
find_package(Threads REQUIRED)

if (MSVC)
    # otherwise msvc will create <bin|lib>/<BUILD_TYPE>/<BUILD_TYPE> hierarchy
    set(OUTPUT_SUBDIR ${CMAKE_GENERATOR_PLATFORM})
else ()
    set(OUTPUT_SUBDIR ${CMAKE_BUILD_TYPE})
endif()

set(ROOT "${CMAKE_SOURCE_DIR}/..")
set(OBJ_DIR "${ROOT}/obj")
set(LIB_DIR "${ROOT}/lib/${OUTPUT_SUBDIR}")
set(BIN_DIR "${ROOT}/bin/${OUTPUT_SUBDIR}")
set(TEST_DIR "${ROOT}/tests/${OUTPUT_SUBDIR}")
set(GEN_DIR "${ROOT}/gen/${OUTPUT_SUBDIR}")
set(DOCS_INPUT_DIR "${ROOT}/docs")
set(DOCS_OUTPUT_DIR "${GEN_DIR}/docs")

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${LIB_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${LIB_DIR}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${BIN_DIR}")

set(CMAKE_CXX_STANDARD 14) # C++14
set(CMAKE_INCLUDE_CURRENT_DIR ON)
if (MSVC)
    set(RT_LINKING_TYPE /MD)
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RT_LINKING_TYPE} /WX /EHsc")
    set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${RT_LINKING_TYPE} /WX /EHsc")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${RT_LINKING_TYPE} /WX /EHsc")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${RT_LINKING_TYPE}d /EHsc")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W2 /MP /EHsc -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0602 -D_WINSOCK_DEPRECATED_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -DASIO_STANDALONE")

    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${RT_LINKING_TYPE} /WX")
    set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} ${RT_LINKING_TYPE} /WX")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${RT_LINKING_TYPE} /WX")
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${RT_LINKING_TYPE}d")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /W3 /MP -D_WIN32_WINNT=0x0602")
else ()
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unknown-pragmas -DASIO_STANDALONE")
    SET(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror -Wno-unknown-pragmas")

    set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
endif ()
